export const AppErrorCode = {
  ALREADY_IN_PARTY: 'ALREADY_IN_PARTY',
  AVATAR_DELETE_FAILED: 'AVATAR_DELETE_FAILED',
  AVATAR_DELETE_RETRY: 'AVATAR_DELETE_RETRY',
  AVATAR_LOAD_FAILED: 'AVATAR_LOAD_FAILED',
  AVATAR_SAVE_FAILED: 'AVATAR_SAVE_FAILED',
  INVITE_LOAD_FAILED: 'INVITE_LOAD_FAILED',
  INVITE_NOT_AVAILABLE: 'INVITE_NOT_AVAILABLE',
  INVITE_UPDATE_FAILED: 'INVITE_UPDATE_FAILED',
  PARTY_CREATION_FAILED: 'PARTY_CREATION_FAILED',
  PARTY_JOIN_FAILED: 'PARTY_JOIN_FAILED',
  PARTY_LEAVE_CLEANUP_PENDING: 'PARTY_LEAVE_CLEANUP_PENDING',
  PARTY_LEAVE_FAILED: 'PARTY_LEAVE_FAILED',
  PARTY_LOAD_FAILED: 'PARTY_LOAD_FAILED',
  PARTY_OWNER_REQUIRED: 'PARTY_OWNER_REQUIRED',
  SCENE_LOAD_FAILED: 'SCENE_LOAD_FAILED',
  SESSION_RESTORE_FAILED: 'SESSION_RESTORE_FAILED',
  USER_LOAD_FAILED: 'USER_LOAD_FAILED',
} as const

export type AppErrorCode = typeof AppErrorCode[keyof typeof AppErrorCode]
